export const reportList = {
  list: {
    report: [
      {
        referredBy: 'Dr. Smith',
        date: '2024-02-01',
        netCharges: '$350.00',
        profFees: '$150.00',
        message: 'Follow-up appointment',
        visitId: 'V12345',
        patient: 'John Doe',
        service: 'Consultation',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Johnson',
        date: '2024-02-02',
        netCharges: '$200.00',
        profFees: '$100.00',
        message: 'Routine check-up',
        visitId: 'V23456',
        patient: 'Jane Smith',
        service: 'Check-up',
        branch: 'Clinic A',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Lee',
        date: '2024-02-03',
        netCharges: '$500.00',
        profFees: '$200.00',
        message: 'MRI scan',
        visitId: 'V34567',
        patient: 'Michael Johnson',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Garcia',
        date: '2024-02-04',
        netCharges: '$150.00',
        profFees: '$80.00',
        message: 'Blood test',
        visitId: 'V45678',
        patient: 'Maria Rodriguez',
        service: 'Laboratory',
        branch: 'Clinic B',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Kim',
        date: '2024-02-05',
        netCharges: '$1000.00',
        profFees: '$400.00',
        message: 'Orthopedic surgery',
        visitId: 'V56789',
        patient: 'David Kim',
        service: 'Surgery',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Patel',
        date: '2024-02-06',
        netCharges: '$120.00',
        profFees: '$60.00',
        message: 'Dental cleaning',
        visitId: 'V67890',
        patient: 'Jessica Patel',
        service: 'Dental',
        branch: 'Clinic C',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Wong',
        date: '2024-02-07',
        netCharges: '$250.00',
        profFees: '$120.00',
        message: 'Eye examination',
        visitId: 'V78901',
        patient: 'Daniel Wong',
        service: 'Ophthalmology',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Martinez',
        date: '2024-02-08',
        netCharges: '$80.00',
        profFees: '$40.00',
        message: 'Vaccination',
        visitId: 'V89012',
        patient: 'Sophia Martinez',
        service: 'Immunization',
        branch: 'Clinic D',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-02-09',
        netCharges: '$180.00',
        profFees: '$90.00',
        message: 'Ultrasound',
        visitId: 'V90123',
        patient: 'Matthew Nguyen',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Hernandez',
        date: '2024-02-10',
        netCharges: '$300.00',
        profFees: '$150.00',
        message: 'Cardiology consultation',
        visitId: 'V01234',
        patient: 'Olivia Hernandez',
        service: 'Consultation',
        branch: 'Clinic E',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-02-11',
        netCharges: '$400.00',
        profFees: '$200.00',
        message: 'Endoscopy',
        visitId: 'V12340',
        patient: 'Ethan Nguyen',
        service: 'Surgery',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Kim',
        date: '2024-02-12',
        netCharges: '$150.00',
        profFees: '$80.00',
        message: 'Routine check-up',
        visitId: 'V23450',
        patient: 'Isabella Kim',
        service: 'Check-up',
        branch: 'Clinic F',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Lee',
        date: '2024-02-13',
        netCharges: '$600.00',
        profFees: '$250.00',
        message: 'X-ray',
        visitId: 'V34560',
        patient: 'Alexander Lee',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Smith',
        date: '2024-02-14',
        netCharges: '$90.00',
        profFees: '$50.00',
        message: 'Dental filling',
        visitId: 'V45670',
        patient: 'Oliver Smith',
        service: 'Dental',
        branch: 'Clinic G',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Johnson',
        date: '2024-02-15',
        netCharges: '$180.00',
        profFees: '$90.00',
        message: 'Pediatric consultation',
        visitId: 'V56780',
        patient: 'Ava Johnson',
        service: 'Consultation',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Patel',
        date: '2024-02-16',
        netCharges: '$400.00',
        profFees: '$200.00',
        message: 'Appendectomy',
        visitId: 'V67890',
        patient: 'Logan Patel',
        service: 'Surgery',
        branch: 'Clinic H',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Wong',
        date: '2024-02-17',
        netCharges: '$120.00',
        profFees: '$60.00',
        message: 'Eye examination',
        visitId: 'V78901',
        patient: 'Amelia Wong',
        service: 'Ophthalmology',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Martinez',
        date: '2024-02-18',
        netCharges: '$80.00',
        profFees: '$40.00',
        message: 'Vaccination',
        visitId: 'V89012',
        patient: 'Lucas Martinez',
        service: 'Immunization',
        branch: 'Clinic I',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-02-19',
        netCharges: '$200.00',
        profFees: '$100.00',
        message: 'MRI scan',
        visitId: 'V90123',
        patient: 'Mia Nguyen',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Hernandez',
        date: '2024-02-20',
        netCharges: '$300.00',
        profFees: '$150.00',
        message: 'Cardiology consultation',
        visitId: 'V01234',
        patient: 'Lucas Hernandez',
        service: 'Consultation',
        branch: 'Clinic J',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-02-21',
        netCharges: '$350.00',
        profFees: '$200.00',
        message: 'Endoscopy',
        visitId: 'V12340',
        patient: 'Sophia Nguyen',
        service: 'Surgery',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Kim',
        date: '2024-02-22',
        netCharges: '$100.00',
        profFees: '$50.00',
        message: 'Dental cleaning',
        visitId: 'V23450',
        patient: 'Ethan Kim',
        service: 'Dental',
        branch: 'Clinic K',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Lee',
        date: '2024-02-23',
        netCharges: '$600.00',
        profFees: '$250.00',
        message: 'X-ray',
        visitId: 'V34560',
        patient: 'Isabella Lee',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Smith',
        date: '2024-02-24',
        netCharges: '$90.00',
        profFees: '$50.00',
        message: 'Dental filling',
        visitId: 'V45670',
        patient: 'Oliver Smith',
        service: 'Dental',
        branch: 'Clinic L',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Johnson',
        date: '2024-02-25',
        netCharges: '$180.00',
        profFees: '$90.00',
        message: 'Pediatric consultation',
        visitId: 'V56780',
        patient: 'Ava Johnson',
        service: 'Consultation',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Patel',
        date: '2024-02-26',
        netCharges: '$400.00',
        profFees: '$200.00',
        message: 'Appendectomy',
        visitId: 'V67890',
        patient: 'Logan Patel',
        service: 'Surgery',
        branch: 'Clinic M',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Wong',
        date: '2024-02-27',
        netCharges: '$120.00',
        profFees: '$60.00',
        message: 'Eye examination',
        visitId: 'V78901',
        patient: 'Amelia Wong',
        service: 'Ophthalmology',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Martinez',
        date: '2024-02-28',
        netCharges: '$80.00',
        profFees: '$40.00',
        message: 'Vaccination',
        visitId: 'V89012',
        patient: 'Lucas Martinez',
        service: 'Immunization',
        branch: 'Clinic N',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-02-29',
        netCharges: '$200.00',
        profFees: '$100.00',
        message: 'MRI scan',
        visitId: 'V90123',
        patient: 'Mia Nguyen',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Hernandez',
        date: '2024-03-01',
        netCharges: '$300.00',
        profFees: '$150.00',
        message: 'Cardiology consultation',
        visitId: 'V01234',
        patient: 'Lucas Hernandez',
        service: 'Consultation',
        branch: 'Clinic O',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-03-02',
        netCharges: '$350.00',
        profFees: '$200.00',
        message: 'Endoscopy',
        visitId: 'V12340',
        patient: 'Sophia Nguyen',
        service: 'Surgery',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Kim',
        date: '2024-03-03',
        netCharges: '$100.00',
        profFees: '$50.00',
        message: 'Dental cleaning',
        visitId: 'V23450',
        patient: 'Ethan Kim',
        service: 'Dental',
        branch: 'Clinic P',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Lee',
        date: '2024-03-04',
        netCharges: '$600.00',
        profFees: '$250.00',
        message: 'X-ray',
        visitId: 'V34560',
        patient: 'Isabella Lee',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Smith',
        date: '2024-03-05',
        netCharges: '$90.00',
        profFees: '$50.00',
        message: 'Dental filling',
        visitId: 'V45670',
        patient: 'Oliver Smith',
        service: 'Dental',
        branch: 'Clinic Q',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Johnson',
        date: '2024-03-06',
        netCharges: '$180.00',
        profFees: '$90.00',
        message: 'Pediatric consultation',
        visitId: 'V56780',
        patient: 'Ava Johnson',
        service: 'Consultation',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Patel',
        date: '2024-03-07',
        netCharges: '$400.00',
        profFees: '$200.00',
        message: 'Appendectomy',
        visitId: 'V67890',
        patient: 'Logan Patel',
        service: 'Surgery',
        branch: 'Clinic R',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Wong',
        date: '2024-03-08',
        netCharges: '$120.00',
        profFees: '$60.00',
        message: 'Eye examination',
        visitId: 'V78901',
        patient: 'Amelia Wong',
        service: 'Ophthalmology',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Martinez',
        date: '2024-03-09',
        netCharges: '$80.00',
        profFees: '$40.00',
        message: 'Vaccination',
        visitId: 'V89012',
        patient: 'Lucas Martinez',
        service: 'Immunization',
        branch: 'Clinic S',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-03-10',
        netCharges: '$200.00',
        profFees: '$100.00',
        message: 'MRI scan',
        visitId: 'V90123',
        patient: 'Mia Nguyen',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Hernandez',
        date: '2024-03-11',
        netCharges: '$300.00',
        profFees: '$150.00',
        message: 'Cardiology consultation',
        visitId: 'V01234',
        patient: 'Lucas Hernandez',
        service: 'Consultation',
        branch: 'Clinic T',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-03-12',
        netCharges: '$350.00',
        profFees: '$200.00',
        message: 'Endoscopy',
        visitId: 'V12340',
        patient: 'Sophia Nguyen',
        service: 'Surgery',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Kim',
        date: '2024-03-13',
        netCharges: '$100.00',
        profFees: '$50.00',
        message: 'Dental cleaning',
        visitId: 'V23450',
        patient: 'Ethan Kim',
        service: 'Dental',
        branch: 'Clinic U',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Lee',
        date: '2024-03-14',
        netCharges: '$600.00',
        profFees: '$250.00',
        message: 'X-ray',
        visitId: 'V34560',
        patient: 'Isabella Lee',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Smith',
        date: '2024-03-15',
        netCharges: '$90.00',
        profFees: '$50.00',
        message: 'Dental filling',
        visitId: 'V45670',
        patient: 'Oliver Smith',
        service: 'Dental',
        branch: 'Clinic V',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Johnson',
        date: '2024-03-16',
        netCharges: '$180.00',
        profFees: '$90.00',
        message: 'Pediatric consultation',
        visitId: 'V56780',
        patient: 'Ava Johnson',
        service: 'Consultation',
        branch: 'Main Hospital',
        status: 'Pending',
      },
      {
        referredBy: 'Dr. Patel',
        date: '2024-03-17',
        netCharges: '$400.00',
        profFees: '$200.00',
        message: 'Appendectomy',
        visitId: 'V67890',
        patient: 'Logan Patel',
        service: 'Surgery',
        branch: 'Clinic W',
        status: 'Scheduled',
      },
      {
        referredBy: 'Dr. Wong',
        date: '2024-03-18',
        netCharges: '$120.00',
        profFees: '$60.00',
        message: 'Eye examination',
        visitId: 'V78901',
        patient: 'Amelia Wong',
        service: 'Ophthalmology',
        branch: 'Main Hospital',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Martinez',
        date: '2024-03-19',
        netCharges: '$80.00',
        profFees: '$40.00',
        message: 'Vaccination',
        visitId: 'V89012',
        patient: 'Lucas Martinez',
        service: 'Immunization',
        branch: 'Clinic X',
        status: 'Completed',
      },
      {
        referredBy: 'Dr. Nguyen',
        date: '2024-03-20',
        netCharges: '$200.00',
        profFees: '$100.00',
        message: 'MRI scan',
        visitId: 'V90123',
        patient: 'Mia Nguyen',
        service: 'Imaging',
        branch: 'Main Hospital',
        status: 'Scheduled',
      },
    ],
  },
};
